server:
  port: 1100
spring:
  application:
    name: service-session-zuul
  main:
    allow-bean-definition-overriding: true
zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    redis-session-service:
      path: /user-session/**
      serviceId: service
      sensitiveHeaders: "*"
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/