server:
  port: 8011
eureka:
  client:
    service-url:
      defaultZone: http://10.96.108.131:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
spring:
  application:
    name: service
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  redis:
    host: 132.232.138.105
    port: 6379
    password:
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    database: 0






